application: gup-traintool
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
-   url: /_ah/spi/.*
    script: main.api_application
    secure: always

# for serving the entire static/assets directory rooting the assets
# directory.

-   url: /assets
    static_dir: frontend/build/assets
    http_headers:
        Vary: Accept-Encoding
    secure: always

# for associating specific url patterns with paths to static files
# uploaded

-   url: /
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    mime_type: text/html; charset=UTF-8
    secure: always


libraries:
-   name: pycrypto
    version: latest

-   name: endpoints
    version: 1.0

-   name: webapp2
    version: latest

-   name: jinja2
    version: latest

skip_files:
-   ^lib/(.*)
-   frontend/app/(.*)
-   frontend/node_modules/(.*)
-   frontend/dependencies/(.*)
-   frontend/test/(.*)
-   frontend/.sass-cache/(.*)