application: gup-traintool
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
-   url: /_ah/spi/.*
    script: main.api_application
    secure: always


libraries:
-   name: pycrypto
    version: latest

-   name: endpoints
    version: 1.0

-   name: webapp2   
    version: latest

-   name: jinja2
    version: latest